### ISSUE TITLE
Consider a helper function for output

### ISSUE THREAD

**Issue by stompweb** [wpmark/wp-post-type-meta#2]
Would be good if there was a function that you could use on archive-{post-type}.php rather than having to use get_option().

Just an example, untested.

``` php

function get_post_type_data($field) {

    $options = get_option('wpptm_' . get_query_var( 'post_type' ));

    $setting = $options[$field];

   return esc_attr($setting);  

}
```

**Comment by wpmark** [comment]
I thought of doing this but then thought if the plugin is turned off the front end would break. Getting the data with a core function is not hard in this case and therefore I would probably prefer to use that. You could always create your own function to do this I guess!

However you could have it there if people want to use it. Therefore I will look at adding this soon.

**Comment by stompweb** [comment]
I guess it depends who is going to be using it. Other advantages to having it:
1. You can escape the content which the user might forget to do (things like the_title() already do this for the user)
2. It enables you to change the inner workings (i.e. if you want to change the wpptm_ prefix or maybe use another method of storage down the line instead of get_option()) without any impact on the end user.
3. It looks nicer in the template :-)

Anyway, leave it up to you!

**Comment by wpmark** [comment]
You are right - have added a function on your advice. It makes sense!

https://github.com/wpmark/wp-post-type-meta/blob/master/wp-post-type-meta.php#L53-L84

**Comment by stompweb** [comment]
Spot on ;-)
