### ISSUE TITLE
Backslashes in text

### ISSUE THREAD

**Issue by MattPostlethwaite** [wpmark/wp-post-type-meta#5]
Hi Mark,

Ran into the issue of getting backslashes in text meta after saving. did a search and found this - http://wordpress.stackexchange.com/questions/6909/how-to-prevent-escaping-when-saving-html-code-in-an-option-value

Found that changing line 35 of functions/meta-update.php fixed this issue
`$wpptm_options[ $key ] = stripslashes( sanitize_text_field( $value[ 'value' ] ) );`

Not fully tested by it fixed my issue.

**Comment by wpmark** [comment]
What text are you adding to where please. I thought this has been corrected and I cannot recreate this issue.

**Comment by MattPostlethwaite** [comment]
I added stripslashes() around `sanitize_text_field( $value[ 'value' ] )` here https://github.com/wpmark/wp-post-type-meta/blob/7139f3bda8724c54f829de65397c5477537815ad/functions/meta-update.php#L35

So this:
`$wpptm_options[ $key ] = sanitize_text_field( $value[ 'value' ] );`

Became:
`$wpptm_options[ $key ] = stripslashes( sanitize_text_field( $value[ 'value' ] ) );`

I thought it was fixed too but it happened when I added an apostrophe to a text box.

**Comment by wpmark** [comment]
Just pushed version 1.0 which should correct this issue. Thanks!

https://github.com/wpmark/wp-post-type-meta/releases/tag/v1.0
